### ISSUE TITLE
CKBull_Hackathon: CKBearn is a transparent, fair online lottery platform.  ckbearn.xyz

### ISSUE THREAD

**Issue by tianlitao** [nervosnetwork/grants#28]
**1、Text Description:** 
CKBearn is a transparent, fair online lottery platform.Log in and place bets using ckbull and joyid.The lottery runs each epoch period, drawing the last character of the first new block's hash to match against participants' transaction hashes for winners who split the prize pool evenly after a 5% service fee (To keep the website running). Bonuses accumulate to the next epoch if no one wins.
**2、Visual Representation:** 
website: https://ckbearn.xyz/
screenshots:
![QQ20230901-104625](https://github.com/nervosnetwork/grants/assets/7892962/bfd4d1cf-365a-4a6a-8078-91b9ead300b1)
![QQ20230901-104711](https://github.com/nervosnetwork/grants/assets/7892962/e589d536-6fb0-4275-ab4b-270e40b39968)
![QQ20230901-104800](https://github.com/nervosnetwork/grants/assets/7892962/c74546b2-f17f-4ff2-bf66-2838034524ba)
![QQ20230901-104808](https://github.com/nervosnetwork/grants/assets/7892962/697f53ca-cf82-466e-8328-4eb0bcabf7a8)
![QQ20230901-104831](https://github.com/nervosnetwork/grants/assets/7892962/9725616d-66ae-44ca-bd61-c64767a13af5)
![QQ20230901-105224](https://github.com/nervosnetwork/grants/assets/7892962/15237d4e-21f3-4f50-95cc-893e9e816e8f)

**Comment by jordanmack** [comment]
Hello @tianlitao, could you share the GitHub repo for your submission with me?

**Comment by tianlitao** [comment]
> Hello @tianlitao, could you share the GitHub repo for your submission with me?

https://github.com/tianlitao/ckbearn
